version: '3'

services:
  ### RDBMS
  # MySQL
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
    - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  ### NoSQL
  # Redis
  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
    - ./docker/redis/data:/data
    command: redis-server
  ### MQ
  # zookeeper for kafka
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  # kafka
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  ### Object Storage
  # minio(S3 like)
  minio:
    container_name: minio
    image: minio/minio
    environment:
      - "MINIO_ACCESS_KEY=MINIO_ACCESS_KEY"
      - "MINIO_SECRET_KEY=MINIO_SECRET_KEY"
    ports:
      - "9000:9000"
    volumes:
      - "./docker/minio/data:/data"
    command: server /data
  # for create bucket on minio
  minioclient:
    container_name: minioc
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 MINIO_ACCESS_KEY MINIO_SECRET_KEY) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/sample;
      /usr/bin/mc policy download myminio/sample;
      exit 0;
      "
### EOF
